# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  web-app-solution: 'WebApp/DevOpsTest.sln'
  schedular-app-solution: 'Schedulars\DevOpsTest.Schedular.sln'
  database-app-solution: 'WebApp/DevOpsTest.sln'
  web-app-build-folder: 'D:\a\1\s\WebApp\DevOpsTest\obj\Release\Package\PackageTmp\'
  schedular-app-build-folder: 'D:\a\1\s\Schedulars\DevOpsTest.Schedular\obj\Release\Package\PackageTmp\'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(web-app-solution)'

- task: VSBuild@1
  inputs:
    solution: '$(web-app-solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(web-app-build-folder)'
    ArtifactName: 'Evolve4-WebApp'
    publishLocation: 'Container'

- task: VSBuild@1
  inputs:
    solution: '$(schedular-app-solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(schedular-app-build-folder)'
    ArtifactName: 'Evolve4-Schedular-App'
    publishLocation: 'Container'