# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ASP.NET CD - Deploy ASP app to Azure Web App

on:
 workflow_run:
   workflows: ["ASP.NET CI - Build Web App and store artifact"]
   types: [completed] #requested

 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

jobs:

  deploy:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: DevOpsTestBuildOutput

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'smeekdevops'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8ED497F3E93141D097F66C6D1F19EE79 }}
          package: .
